### ISSUE TITLE
small typo, pg.XXXV (pdf viewer page 35) preface, version - 2022-02-28

### ISSUE THREAD

**Issue by tingtang2** [probml/pml2-book#10]
in second paragraph of preface, "latent varibale" --> "latent variable"

**Comment by pat749** [comment]
he can you specify it because i am not able to see it in that page.

**Comment by tingtang2** [comment]
Hey sorry, I changed the page number to reflect the fact that the typo is in the Preface to the entire book, after the table of contents, technically before page "1"

**Comment by murphyk** [comment]
fixed, thanks
