### ISSUE TITLE
Page 839, Line 17; sign of the constant term; version 2022-07-01

### ISSUE THREAD

**Issue by vaseline555** [probml/pml2-book#103]
Hi, this is Adam.

I would like to thank all authors in advance for the open of this great material to the public.
I am worrying that this question may be originated from my ignorance, but I wonder if the explanation on the equivalence of MLE with minimizing KL divergence is correct or not.

TL; DR; Shouldn't the minus sign contained in the constant term be removed?

At the end of the first paragraph (line 17), the constant term is equal to  `-\mathbb{E}_{\mathbf{x} \sim p_{\text {data }}(\mathbf{x})}\left[\log p_{\text {data }}(\mathbf{x})\right]`.
I think the minus sign at the very front of the constant term should be removed, for `p_{\text {data }}(\mathbf{x})}\integral[\log p_{\text {data }}(\mathbf{x})` be cancelled out by the term that can be separated from the denominator of subsequent KL divergence term, so that it becomes equivalent to the `\mathbb{E}_{\mathbf{x} \sim p_{\text {data }}(\mathbf{x})}\left[\log p_{\boldsymbol{\theta}}(\mathbf{x})\right]` (i.e., eqn. 24.5; line 8).

Could you please check this out?
Please let me know if I think in a wrong way.
Thank you.

Best,
Adam

**Comment by murphyk** [comment]
It should be `log-lik = -KL(pdata | pmodel) + const` where `const = pdata log pdata`.
