### ISSUE TITLE
Typo in 3.5.2.1 page 88 of 2022-07-07 version

### ISSUE THREAD

**Issue by YuchiLiuS** [probml/pml2-book#104]
In 3.152, the result should be \phi^x(\phi+1)^{-n} instead of \phi^x(\phi+1)^{-x}
In 3.155, the right hand side probably should be -\frac{x}{\phi^2}+\frac{n}{(\phi+1)^2} instead of -\frac{x}{\phi^2}-\frac{n}{(\phi+1)^2}

**Comment by murphyk** [comment]
fixed
