### ISSUE TITLE
Jefferys prior in page 89 Equation 3.160 of 2022-07-07 version

### ISSUE THREAD

**Issue by YuchiLiuS** [probml/pml2-book#105]
In 3.5.2.3 Equation 3.160 Should the last element of FIM be \frac{1}{1\2sigma^4} instead of \frac{2}{\sigma^2} according to equation 2.239 since we are switching from \upsilon to \sigma^2?
Then \sqrt(det(F(\theta))) = \sqrt(\frac{1}{2\sigma^6}), and 3.161 becomes p(\mu, \sigma^2) \propto \frac{1}{\sigma^3} instead of \frac{1}{\sigma^2}.

**Comment by YuchiLiuS** [comment]
A related section is 3.5.3.2, along line 46, this result probably needs more explanation, it is not evident based on Equation 2.239, that F(\sigma)=\frac{2}{\sigma^2: there is a transformation of variable from Equation 2.239 from F(v=\sigma^2) to F(\sigma).
F(\sigma)=F(v)[\frac{dv}{d\sigma}]^2=\sqrt(\frac{1}{2\sigma^4})*(2\sigma)^2=\frac{2}{sigma^2}

**Comment by murphyk** [comment]
The issue is explained here 
https://www.stat.cmu.edu/~kass/papers/rules.pdf
Corrected text below
<img width="625" alt="Screen Shot 2022-07-28 at 9 52 20 PM" src="https://user-images.githubusercontent.com/4632336/181685484-19934f06-5d3e-4ca0-82fb-f12a46c2db87.png">
