### ISSUE TITLE
Page 92 Equation 3.175 version 2022-07-07

### ISSUE THREAD

**Issue by YuchiLiuS** [probml/pml2-book#107]
In 3.6.1 hierarchical binomial model, in equation 3.175, we assume p(\mu, \sigma) \propto 1 Then p(a,b) \propto (a+b)^(-5/2).
However the derivation is not very clear to me. 
It seems to assume `\sigma = (a+b)^(-1/2)`, then as` \mu= \frac{a}{a+b}`, With Jacobian over the change of variables,
then we can get `p(a,b) = p(\mu, \sigma) * \begin{vmatrix}
\frac{\partial \mu}{\partial a}&\frac{\partial \mu}{\partial b}\\
\frac{\partial \sigma}{\partial a}&\frac{\partial \sigma}{\partial a}
\end{vmatrix}
 \propto (a+b)^(-5/2)`

However, \sigma for Beta distribution is equal to `[\frac{ab}{(a+b)^2*(a+b+1)}]^(1/2)`, which is not equal to `(a+b)^(-1/2)`, under what condition would the former be approximated with the latter?

**Comment by murphyk** [comment]
I agree it's not clear. The prior `p(a,b) propto (a+b)^{-5/2}` is from 

https://www.pymc.io/projects/examples/en/latest/generalized_linear_models/GLM-hierarchical-binomial-model.html

I have clarified the text to drop the reference to the beta distribution.
