### ISSUE TITLE
Error page 623, relationship cold & tempered priors

### ISSUE THREAD

**Issue by djmarti** [probml/pml2-book#11]
Page 623 (printed on book, not viewer page), line 36. The relationship should be $\tilde{\sigma}^{2} = \sigma^{2} / T$, i.e., it should involve variances, not standard deviations.

Version: 28 Feb 2022.

**Comment by murphyk** [comment]
You are right. I rewrote this section since it was unclear.
<img width="642" alt="Screen Shot 2022-03-02 at 10 32 41 AM" src="https://user-images.githubusercontent.com/4632336/156425812-133f6018-1789-4c6f-853d-74b62e61926c.png">
