### ISSUE TITLE
Typo in equation 2.87, 2.107, 2.111 in July 21 2022 version

### ISSUE THREAD

**Issue by zou000** [probml/pml2-book#113]
![Screenshot_2022-07-24-00-10-58-53_c0fc23361849dfc0a4b4c6dd2adcac79](https://user-images.githubusercontent.com/482689/180636541-a7394bc3-a75c-422e-94a9-03c7e3174d20.jpg)

Should be $KSK^T$

![Screenshot_2022-07-24-00-33-08-71_c0fc23361849dfc0a4b4c6dd2adcac79](https://user-images.githubusercontent.com/482689/180637155-230fa692-3f8a-4380-a3c5-444d823953cf.jpg)

Also typo in eq. 2.107 ($-1^T$) and 2.111($-T$)

**Comment by murphyk** [comment]
fixed, thanks
