### ISSUE TITLE
Approximate nonlinear Gaussian BP (version Jul 29, 2022)

### ISSUE THREAD

**Issue by e-pet** [probml/pml2-book#118]
Thanks for creating this amazing resource! :-) I have some minor suggestions regarding the characterization of two papers I was involved in.

You currently write (p. 371, section 3.8.4 on Inference for state-space models / inference based on statistical linearization):
> In [HPR19] they extend IPLS [Iterated Posterior Linearization Smoother] to belief propagation in Forney factor graphs (Section 4.6.1.2), which enables the method to be applied to general graphical models with Gaussian potentials but nonlinear
dependencies

and (p. 392, section 3.9.2. on Inference for graphical models / Loopy BP / Gaussian BP):
> To perform message passing in models with non-Gaussian potentials, we can extend the techniques from Section 8.5.2 from chains to general graphs. For example, we can use local linearization, similar to extended Kalman filter (see [PHR18]); or we can use sigma point BP [MHH14], similar to unscented Kalman filter.

These characterizations are not entirely precise.
- As you'll be well aware, any method that maps Gaussians to Gaussians can be interpreted as a local linearization, so this is true for both EKF-style methods (which linearize using the Jacobian) and sigma point / other quadrature methods (which typically perform statistical linearization / moment matching).
- In [PHR18], we describe a general method (including explicit message update rules) to perform nonlinear approximate Gaussian BP in FFGs using quadrature / sigma point methods (UKF/S, Cubature, or Gauss-Hermite filtering/smoothing, etc.). We have an example where we derive a novel nonlinear MBF smoother, but the method is really general and applicable to any FFG. We do _not_ do any Jacobian-based linearization / EKF-style things here, and we focus on the non-iterative setting.
- In [HPR19], we describe a general linearization formulation (again including explicit message update rules) for nonlinear approximate Gaussian BP, where the linearization can be Jacobian-based ("EKF-style"), statistical (moment matching / quadrature filtering / sigma points), or anything else. Moreover, we discuss how any such linearization method can benefit from iterations. This encompasses the IPLS as a very special case, but also basically any other conceivable iteration scheme in state-space models or any other (e.g., loopy) FFGs.

Hope this helps and does not come across as picky / vain. :-)

Thanks again for your tremendous efforts!

**Comment by murphyk** [comment]
ok, i rewrote the sec on p371 as follows
```
In \citep{Herzog2019} they extend IPLS to belief propagation
in Forney factor graphs (\cref{sec:FFG}),
which enables the method to be applied to a large class of graphical models
beyond \SSMs. In particular, they give a general linearization formulation
(including explicit message update rules) for nonlinear approximate Gaussian BP
(\cref{sec:gaussBP})
where the linearization can be Jacobian-based (``EKF-style''), statistical
(moment matching / quadrature filtering / sigma points), or anything else.
They also show how any such linearization method can benefit from iterations.
```
and on p392 as follows
```
To perform message passing in models with non-linear (but Gaussian) potentials,
we can generalize the extended Kalman filter
techniques from \cref{sec:EKF}
and the moment matching techniques (based on quadrature / sigma points)
from \cref{sec:GGF,sec:statlin}
from chains to general factor graphs
(see e.g., \citep{SigmaBP,Petersen2018,Herzog2019}).
```
is this correct?

**Comment by e-pet** [comment]
Yes, that looks perfect! Thanks a lot. 😊
