### ISSUE TITLE
Book 2, version 2022-08-08, section 6.10

### ISSUE THREAD

**Issue by behrman** [probml/pml2-book#126]
pages 292 - 295: I recommend replacing formulas K, M, K2, DK, DK2 with sequential formula numbers as in the rest of the book. M and DK2 are each used twice, leading to very confusing statements such as "Going from (DK2) to (DK2)" (page 295, line 10).

page 291, line 18: To be consistent with rest of book: § -> Section
page 292, formula K: $P^\top \boldsymbol{1}_m = \mathbf{b}$ -> $P^\top \boldsymbol{1}_n = \mathbf{b}$
page 293, line 28: The math on this line doesn't make sense to me
page 295, formula 6.245: $f\text{1-Lipschitz}$ -> $f\in\text{1-Lipschitz}$
page 297, line 41: should discourage further users -> should further discourage users
page 298, formula 6.254: $P^\top \boldsymbol{1}_m = \mathbf{b}$ -> $P^\top \boldsymbol{1}_n = \mathbf{b}$
page 298, line 26: Where and is itself -> ??

**Comment by murphyk** [comment]
ok, i fixed all these issues except `page 293, line 28`. I'd have to ask Marco about that...
