### ISSUE TITLE
Three typos

### ISSUE THREAD

**Issue by kurtwzhao** [probml/pml2-book#13]
Feb 28 2022 version
The page number is the printed one

p.29, the last line of the first paragraph of Section 2.5.1, "In Section 2.5.3, we show that A is a convex function over the **concave set**". I believe it should be convex set instead of concave set

p.42, equation (2.237), it should be the plus sign instead of the minus sign

p.303, the line above equation (7.8), he --> the

**Comment by murphyk** [comment]
fixed, thanks
