### ISSUE TITLE
Request or suggestion: chapter enumeration in PDF's bookmarks

### ISSUE THREAD

**Issue by avm19** [probml/pml2-book#140]
The PDF bookmarks do not include chapter numbers. I wonder if this is deliberate and if there is any chance the numbers could be included in the future? With the section/subsection/chapter bookmarks enumerated, the navigation would be a bit easier for those who use them.

Many thanks for your books, Prof. Murphy.
![image](https://user-images.githubusercontent.com/52547519/185722754-92a14430-856b-456d-bfdb-91f5e91af483.png)
[2022-08-15 version]

**Comment by murphyk** [comment]
how do I make this happen in latex?

**Comment by avm19** [comment]
> how do I make this happen in latex?

Assuming your document uses `hyperref` (and no other fancy packages controlling specifically this behaviour), the numbering is added by the `bookmarksnumbered` option in `hyperref`:

```\usepackage[bookmarksnumbered]{hyperref}```

I found [this answer](https://tex.stackexchange.com/questions/35422/partition-numbering-and-pdf-bookmark-generation/35430#35430), which explains the details. The example provided there works on my system (except that `\usepackage{babel}` is now required by `lipsum`).

**Comment by murphyk** [comment]
ok, i've added this, it will appear in the next release (later tonight :)
