### ISSUE TITLE
Typo in Section 5.6.2 Variational IB

### ISSUE THREAD

**Issue by jperlin** [probml/pml2-book#145]
Book downloaded Aug 20th 2022.

In sentence following the sentence 'To explain the method in more detail, let us define the following notation.', the decoder should be $d(y|z)$ instead of $d(z|y)$.

**Comment by lkhphuc** [comment]
Equation 5.177, line 17-18 in this section also misses a `log` around <m(z)>.

**Comment by murphyk** [comment]
fixed thx
