### ISSUE TITLE
Typo near eq 28.147

### ISSUE THREAD

**Issue by ceroytres** [probml/pml2-book#147]
Near eq 28.147, the book reads "... use the logistic distribution, discussed in Section 15.4.1. The corresponding log pdf, for the case where the mean is zero and the variance is 1, is given by the following:". In order to get eq 28.147, the scale parameter of the logistic distribution needs to be $\sqrt{3}/\pi$ rather than 1?

Book downloaded 8-25-22 and page number: 930

**Comment by ceroytres** [comment]
Also quick question, for the whitening transform $\Sigma^{-1/2}$ in eq. 28.149. Should it be $S^{-1/2}U^{T}$ where $S$ are eigenvalues and $U$ the eigenvectors of $\Sigma$ (e.g. $S,U=\text{eig}(\Sigma)$ ).

Seems to be consistent with these sources:
- [Lecture](https://www.stat.cmu.edu/~ryantibs/convexopt-F13/lectures/20-ICA.pdf)
- the ICA implementation in [sklearn](https://github.com/scikit-learn/scikit-learn/blob/36958fb240fbe435673a9e3c52e769f01f36bec0/sklearn/decomposition/_fastica.py#L560)
- And the reference code listed in the book [here](https://github.com/tuananhle7/ica/blob/57c74049a5a9f17dd25733a36a01c7145c5711d7/ica.py#L167)

**Comment by murphyk** [comment]
yes, the variance is 1, but s=sqrt(3)/pi. I've clarified this.

<img width="839" alt="Screen Shot 2022-10-16 at 10 16 00 PM" src="https://user-images.githubusercontent.com/4632336/196094740-8aa1af92-d9fd-47da-9056-5a19c7be9b0d.png">
