### ISSUE TITLE
Whitening transform in ICA question

### ISSUE THREAD

**Issue by ceroytres** [probml/pml2-book#148]
Also quick question, for the whitening transform $\Sigma^{-1/2}$ in eq. 28.149. Should it be $S^{-1/2}U^{T}$ where $S$ are eigenvalues and $U$ the eigenvectors of $\Sigma$ (e.g. $S,U=\text{eig}(\Sigma)$ )? I think $\Sigma^{-1/2}$ is  ZCA whitening while $S^{-1/2}U^{T}$ is PCA whitening.

$S^{-1/2}U^{T}$ seems to be consistent with these sources:

- [Lecture](https://www.stat.cmu.edu/~ryantibs/convexopt-F13/lectures/20-ICA.pdf)
- the ICA implementation in [sklearn](https://github.com/scikit-learn/scikit-learn/blob/36958fb240fbe435673a9e3c52e769f01f36bec0/sklearn/decomposition/_fastica.py#L560)
- And the reference code listed in the book [here](https://github.com/tuananhle7/ica/blob/57c74049a5a9f17dd25733a36a01c7145c5711d7/ica.py#L167)

page number: 930 and date: 8-25-22

**Comment by murphyk** [comment]
let me look into this.
