### ISSUE TITLE
Chap 19 Structured Prediction

### ISSUE THREAD

**Issue by simonjdprince** [probml/pml2-book#15]
Feb 28 2022 version

P712 L44 "PGM-D" has not been defined nearby
P712 L46 "less modular much slower" --> "less modular and much slower"
P713 L39  I think p(BIO_{1:T}, POS_{1:T}|words_{1:T|) might be clearer
P714 L41 I'm not an expert I think what you are describing here is a PCFG in Chomsky normal form (or almost, there should be another production rule that yields an empty string).  I general PCFG can have more general production rules like C->Baa
P717 L1 "Convolutional networks or CNNs"   This reads strangely as if these are two different things.
P719 Eq 19.14.  I think you have swapped here from (i) x being the data and inferring y to (ii) y being the data, x being an "exogenous variable" and inferring z.  I could be wrong but if so then clarifying this change of notation (or better not changing it) would be helpful.
P721 L31 Open bracket with no close bracket
P726 L45 sentence ends with "and"
P727 L8 trends is --> trends are /  trends is --> trend is
P729 L19 "in top row"  Might have understood this, but I think the observations are the y's which are in the second row.

**Comment by murphyk** [comment]
thanks, fixed
