### ISSUE TITLE
Error: Table 4.3 Probability does not add up to 1 in row 2 and 3

### ISSUE THREAD

**Issue by lkhphuc** [probml/pml2-book#155]
Version: Camera-ready 22nd August

For rows 2 and 3, $\hat{\theta}_{i,j,k} = [\frac 0 4, \frac 0 4 \frac 1 4]$ which do not add up to one. I believe the division by 4 is a typo mistake, according to Eq. 4.47.

<img width="834" alt="image" src="https://user-images.githubusercontent.com/12573521/189327858-65e10783-7602-46ee-89ec-78c08a0d1f98.png">

**Comment by murphyk** [comment]
fixed, thanks
