### ISSUE TITLE
Adding reference to "Convex Combination Belief Propagation Algorithms" by Anna Grim and Pedro Felzenszwalb

### ISSUE THREAD

**Issue by martinResearch** [probml/pml2-book#156]
This is an amazing book!

I believe that it would be worth adding in section 9.3.4  some lines to discuss the simple method to guaranty convergence of loopy BP  described in *Convex Combination Belief Propagation Algorithms* by Anna Grimand Pedro Felzenszwalb
[arxiv](https://arxiv.org/abs/2105.12815).

Abstract:

_We present new message passing algorithms for performing inference with graphical models. Our methods are designed for the most difficult inference problems where loopy belief propagation and other heuristics fail to converge. Belief propagation is guaranteed to converge when the underlying graphical model is acyclic, but can fail to converge and is sensitive to initialization when the underlying graph has complex topology. **This paper describes modifications to the standard belief propagation algorithms that lead to methods that converge to unique solutions on graphical models with arbitrary topology and potential function**_

It seems that is has been submitted (http://annamgrim.com/publications.html) but not published yet.

**Comment by murphyk** [comment]
I've added a citation to this version

A. Grim and P. Felzenszwalb, “Convex Combination Belief Propagation Algorithms,” arXiv [cs.AI], May 26, 2021 [Online]. Available: http://arxiv.org/abs/2105.12815
