### ISSUE TITLE
Typos in Diffusion Chapter

### ISSUE THREAD

**Issue by ceroytres** [probml/pml2-book#160]
Eq 25.41- 25.42 seem to drop the conditioning on  $x_0$ and the expectation should be $E_{q(x_{1:T}|x_0)}$.

The diffusion loss in Eq (25.48) in the current version reads as
$$=\sum_{t=2}^T \text{KL}(q(x_{t−1}|x_t, x_0) || p_\theta(x_{t−1}|x_t))$$ 

I think it should read 

$$ =\sum_{t=2}^T E_{q(x_t|x_0)} [ \text{KL}(q(x_{t−1}|x_t, x_0) || p_\theta(x_{t−1}|x_t))]$$ 

[Steps for derivation](https://github.com/probml/pml2-book/files/9622245/temp.2.pdf)

This seems to be consistent with the conclusion of https://arxiv.org/abs/2208.11970 in eq 58

Downloaded the book on 9-21-2022

**Comment by murphyk** [comment]
You're right. Fixed, thanks
