### ISSUE TITLE
Reference of random Fourier features

### ISSUE THREAD

**Issue by zjowowen** [probml/pml2-book#167]
Hi,
In section of random Fourier features, pdf page 685, section 18.2.6, the formula 18.42 and 18.43 should be attributed to another paper, "On the Error of Random Fourier Features" Sutherland and Schneider, of which the RFF form is z=[cos(wx),sin(wx)].
The origin RFF form seems to  be z=cos(wx+b) in Rahimi and Recht's paper.

**Comment by murphyk** [comment]
fixed, thanks
