### ISSUE TITLE
Chap 7 Inference Algorithms overview

### ISSUE THREAD

**Issue by simonjdprince** [probml/pml2-book#17]
Feb 28th version
(I thought this chapter was really great BTW)

P302 Figure 7.1  you should probably mention what solid vs empty circles mean
P303 L2 "a combination known variational EM"
P303 L14 You should probably define SVI somewhere
P303 L39 "he unknown variables"
P303 Eq 7.8  might be good to define \mathcal{T}(\boldsymbol \theta)
P303 Eq 7.10 Something wrong here.  I suspect it's supposed to be two equations and there's a \\ missing
P304 Eq 7.13 puzzled me but I am quite stupid so it might be right.  I guess what is confusing me is that when we integrate a function by dividing it into bars, there needs to be some sense of the width of the bars.  Otherwise, this denominator will just get bigger as K increases whereas it should just become closer to the normalization constant.
P304 Eq 7.14  Technically either Bern(y_n|\theta) or something like Bin_{1}(y_{n}, \theta).
P305 Fig 7.2 (and elsewhere).  Tsk... axis labels please.
P306 Fig 7.3c Is this supposed to be increasing? and if so could you plot a smoothed version to show that
P306 Fig 7.3d It's a bit yucky that this goes below zero out of the valid range of the parameters.  I assume due to the kernel density process.
P307 Eq 7.22.  This is a key chapter for getting the main ideas of inference down;  I think this equation could use an extra line. At the moment, you both add in the defn of KL divergence and use Bayes rule in a single step without either being defined nearby which is a lot to take if you don't already know all this stuff.
P309 L42 It seemed weird to consider this a uniform noise model, given that it's variance is a 10th of the noiseless data value.  Just maybe double check this is right.  It would have made more sense to me if the variances were the other way around.
P310 Fig 7.5.  Not an error, but it just made me laugh that the Laplace approximation does so well.

**Comment by murphyk** [comment]
Thanks a lot. I've fixed all these issues except p309 L42. It seems right to me: 
<img width="646" alt="Screen Shot 2022-03-14 at 3 12 37 PM" src="https://user-images.githubusercontent.com/4632336/158269702-9e4eff8a-a9ff-4194-bba0-d1b6641a438d.png">

Here the observation x_i is either tightly centered on the truth, z, or is drawn from a broad N(0,10) distribution, which seems reasonable. It also seems to match [Minka's matlab code](https://github.com/tminka/ep-clutter-example/blob/main/test_clutter.m#L6).
