### ISSUE TITLE
Typo: Chap 25

### ISSUE THREAD

**Issue by EverettYou** [probml/pml2-book#182]
* Sec 25.1.1. In both Eq. (25.5) and (25.11), regarding the definition of conditional variance, $\alpha_{t|s}^s$ should be replaced by $\alpha_{t|s}^2$.
* Sec 25.1.2. Page 835 line46, $p(\mathbf{x}_0|\mathbf{z}_z)$ should be $p(\mathbf{x}_0|\mathbf{x}_1)$?
* Sec 25.1.3.2 The symbols $\mathbf{z}_s$, $\mathbf{z}_t$ are not defined, seem to mean $\mathbf{x}_s$, $\mathbf{x}_t$.

**Comment by murphyk** [comment]
I've completely rewritten the diffusion chapter - will post new version soon
