### ISSUE TITLE
 Question on HMM learning. Version 20221016.

### ISSUE THREAD

**Issue by Rajon010** [probml/pml2-book#186]
The two statements are somehow contradicting. Can we get stuck at local optima?
![Screenshot from 2022-11-29 14-21-42](https://user-images.githubusercontent.com/11660172/204454437-e339cabd-e409-4b42-98ba-468133fbf830.png)
![Screenshot from 2022-11-29 14-20-54](https://user-images.githubusercontent.com/11660172/204454428-e54238ca-8a3a-4706-bc62-534e98c0b4be.png)

**Comment by murphyk** [comment]
Clarified remark to be ` (In fact, if suitably initialized,
 the method  can be shown to converge to (close to) one of the global
optima \citep{Yang2015}.)'
