### ISSUE TITLE
Missing figure values: Figure 2.22, Page 61, Lines 1-14 (pdf), Version: 2022-10-16

### ISSUE THREAD

**Issue by DonnaVakalis** [probml/pml2-book#187]
Figure 2.22: The sub-plot title (e.g., the value of the bandwidth parameter) is needed to understand each sub-figure (a), (b) and (c)

**Comment by murphyk** [comment]
Good point. The source figures at http://www.gatsby.ucl.ac.uk/~gretton/papers/neurips19_1.pdf don't specify sigma, but it decreases from left to right, so I now mention that.
