### ISSUE TITLE
Mistake in text: Chapter 4.4.2.2, Page 122, lines 40-41 (pdf), Version: 2022-10-16

### ISSUE THREAD

**Issue by DonnaVakalis** [probml/pml2-book#190]
Text says "since it is more likely that the low grade is explained by the class being hard"
but that is not correct...
The low grade could be explained by the class being hard, but is *more likely* explained by the student having low intelligence.  
This correction is consistent with the text further on, in Section 4.2.6.1 where the example is revisited and correctly explained. 

The sentence in 4.4.2.2 should be revised to match and more clearly contrast low-intelligence vs difficult class, rather than the way it is worded now, as high vs difficult  (as the latter are not competing explanations).

**Comment by murphyk** [comment]
good point, fixed
