### ISSUE TITLE
Initialism without its words: Chapter 2.27.5 (pg 24, lines 15-18) and 4.3.3.4  (pg 150 , line 44 )  PDF Version: 2022-12-24

### ISSUE THREAD

**Issue by DonnaVakalis** [probml/pml2-book#196]
Just a heads up: this is the first time DNN appears in the text. 
Even though it's a common initialism, maybe should be spelled out?

**Comment by DonnaVakalis** [comment]
Chapter 2.27.5 (pg 24, lines 15-18)
Another initialism that appears 100 pages before it's introduced in words: CPD

**Comment by murphyk** [comment]
fixed
