### ISSUE TITLE
Typo : Figure 4.55 (pg 191, lines 10-24) PDF Version: 2022-12-24

### ISSUE THREAD

**Issue by DonnaVakalis** [probml/pml2-book#198]
Typo in the bottom-righthand node of Figure 4.55:
A_j = 0 should be A_j = 1 to match the text description.

**Comment by murphyk** [comment]
Fixed. (Actually there is a bigger problem with the figure: the arrow should go from A to Y!)

**Comment by DonnaVakalis** [comment]
Ha... Yes! I was scratching my head about that... and thought you must have another way of drawing causal diagrams (e.g., I've never seen someone explicitly add a node for 'A')
