### ISSUE TITLE
20.2.3 Covariate shift

### ISSUE THREAD

**Issue by bsuleymanov** [probml/pml2-book#21]
1) "In this section, we consider covariate shift, which refers to discriminative classifiers of the form p(X)p(Y|X) where p(X) changes"
Why are these classifiers called discriminative and not generative? (Since we learn p(x) to generative x)?

2) In "discriminative classifiers of the form p(X)p(Y|X)" and "For a discriminative model of the form p(y|x)": does x and X mean the same thing in this context, or is letter case important here? (I looked at notation section in the first book, it said that notation is context dependent).

**Comment by murphyk** [comment]
I was a bit sloppy there. I changed it to

In this section, we consider \keywordDef{covariate shift},
which refers to settings in which we model
the joint as $p(\vx,\vy) = p(\vx) p(\vy|\vx)$,
and we assume $p(\vx)$ changes while $p(\vy|\vx)$ is constant.
