### ISSUE TITLE
Potential Mistake in Chapter 34.5.5 [version 2023-01-19]

### ISSUE THREAD

**Issue by sunjink1m** [probml/pml2-book#211]
Equation (34.83) in Chapter 34.5.5 should instead look like

$$Q_* (s,a) =  R(s,a) + \gamma \mathbb{E}_{p_T (s'|s,a)} [ \max_{a'} {Q_*} (s',a') ] $$

, with the $\max$ and the $\mathbb{E}$ switched.

This will be identical to the last equation seen in page 90 of Sutton and Barto's book:

https://web.stanford.edu/class/psych209/Readings/SuttonBartoIPRLBook2ndEd.pdf

This makes sense because we need to choose the best action _given_ the next state, $s'$, not choose it before the next state is observed.

**Comment by murphyk** [comment]
Yes, good catch.
