### ISSUE TITLE
A tiny typo in Chapter 5 (information theory) from version (2023-01-19)

### ISSUE THREAD

**Issue by YifanMath** [probml/pml2-book#212]
In the beginning paragraph (page 217), "wow do we measure it?" should be "how do we measure it?".

**Comment by subminu** [comment]
There is a missing right parenthesis in 5th line of the same page.

"We'll study the properties of the KL divergence and two special cases: entropy **(Section 5.2**, and mutual information (Section 5.3)."

**Comment by murphyk** [comment]
fixed, thx
