### ISSUE TITLE
Error in one formula (24.29)

### ISSUE THREAD

**Issue by Thib712** [probml/pml2-book#213]
Here what's currently written:
![image](https://user-images.githubusercontent.com/123693583/214955685-b42b24b0-1339-4fe3-b847-b704ae26891a.png)
I think the formula should instead be 
![Screenshot from 2023-01-26 13-35-39](https://user-images.githubusercontent.com/123693583/214956488-74fa671b-297f-46cc-a556-6e7f051e2ac8.png)

Indeed the paper it refers to states:
![image](https://user-images.githubusercontent.com/123693583/214956718-156ef853-935e-4b1c-af6f-ff1c8584fd5e.png)

In our parametrization:
$\psi_i(x, \theta) = \frac{\partial \log p_{\theta}(x)}{\partial x_i}= -\frac{\partial \varepsilon _{\theta}(x)}{\partial x_i}$

Therefore
$\partial_i \psi_i(x, \theta) = -\frac{\partial^2 \varepsilon _{\theta}(x)}{{\partial x_i}^2}$

**Comment by murphyk** [comment]
fixed, thx
