### ISSUE TITLE
typo 25.4.4 Reverse diffusion ODE 2023-01-19

### ISSUE THREAD

**Issue by jgarcke** [probml/pml2-book#214]
p. 870, l. 36 
However, in practice one can get better results using higher-order ODE solvers, such as Heung’s
method

should be Heun's method, the second order ODE solver ?

and while I am here:
p. 1122, l34 This is a linear system of equations in |S| unknowns, We c −1  Alternatively, we can use value iteration by co
either . to end the sentence or a small we

and (sorry for having separate things here) next line:
Alternatively, we can use value iteration by computing...
but since in value iteration the policy implicitly gets updated, one either writes
Alternatively, we can iteratively solve by computing... or mention to use instead of the max_a the a from pi in the value iteration.

**Comment by murphyk** [comment]
I fixed ref to Heun's method, but did not understand your second comment. Maybe you can highlight the error and upload? 

<img width="643" alt="Screenshot 2023-04-01 at 6 40 08 PM" src="https://user-images.githubusercontent.com/4632336/229326418-83a0d9c1-c98b-4961-b4e6-661a016d9526.png">
