### ISSUE TITLE
Minor typo in equation, missing '

### ISSUE THREAD

**Issue by sunilsu** [probml/pml2-book#215]
version "Draft of “Probabilistic Machine Learning: Advanced Topics”. January 22, 2023"
Page: 404

In setting up Eq 9.44,

Currently, $\lambda_t(j) =  -log\ p(y_t|z_t=j)$
Should it be, $\lambda_t^{'}(j) =  -log\ p(y_t|z_t=j)$ ?

**Comment by murphyk** [comment]
fixed, thx
