### ISSUE TITLE
Minor typo in inline maths page 433 section 10.1.1

### ISSUE THREAD

**Issue by MDCHAMP** [probml/pml2-book#224]
Paragraph below equation 10.4 reads as:

The final term $\log p_\theta(x) = \int p_\theta(x, z) \text{d}z$ is generally intractable to compute.

Should read:

The final term $\log p_\theta(x) = \log \int p_\theta(x, z) \text{d}z$ is generally intractable to compute.

**Comment by murphyk** [comment]
fixed, thx
