### ISSUE TITLE
typo in equations 33.33 and 33.44

### ISSUE THREAD

**Issue by rhaslingerinmarket** [probml/pml2-book#225]
In equations 33.33 and 33.44 the denominators of the left hand sides should, I believe, be squared. The units are off otherwise and doesn't seem to agree with the Bayes Rule for Gaussians.

**Comment by murphyk** [comment]
what page are you referring to? I don't see any Gaussians in ch 33 (vol 2

**Comment by rhaslingerinmarket** [comment]
my apologies.  I mistyped I meant 34.33 and 34.44. In the version I just downloaded from your site this is on page 1106 at the top.

**Comment by murphyk** [comment]
You are right. Fixed. Thanks.
