### ISSUE TITLE
16.2.7 Are the embedding multiplications left multiplies when they should be right?

### ISSUE THREAD

**Issue by cottrell** [probml/pml2-book#226]
![image](https://user-images.githubusercontent.com/223276/221247014-c4528e04-3076-4927-b5e9-c9d2a1cf8a16.png)

i.e. $K=XW^K \in R^{n \times d_k}$ not $K = W^K X$ 

And if so I think $x \in R^d$ and $y_i \in R^{d_y}$ not $d_k$ and $d_v$.

**Comment by ericauld** [comment]
Related: https://github.com/probml/pml2-book/issues/227

**Comment by murphyk** [comment]
fixed, thx
