### ISSUE TITLE
Typos in Section 5 (pages 234 and 237), PDF Version 20213-01-22

### ISSUE THREAD

**Issue by DonnaVakalis** [probml/pml2-book#233]
Section 5.2.2, Page 234, Line 24: 
Missing parentheses around mention of Section 5.1.2.3 i.e.,  "of KL divergence Section 5.1.2.3. "

Section 5.3.2, Page 237, Line 9.5: 
Written as "tells is that" but should be "tells us that"

**Comment by murphyk** [comment]
fixed
