### ISSUE TITLE
Collected Typos across Section 6, PDF Version 20213-01-22

### ISSUE THREAD

**Issue by DonnaVakalis** [probml/pml2-book#234]
Section 6.4.3, Page 276, Equation 6.9.1: There are two opening parentheses on x_1 instead of a single opening parenthesis 

Section 6.4.5.1, Page 279, Line 33:  "where c_ij = 1/2 [is] i = j"... the "is" should be "if" 

Section 6.5.4, Page 286, Line 11:  "hard to maximize[.] since we cannot" change period to a comma or delete altogether

Section 6.6.1,Page 292,  Figure 6.10:  The figure description switches the correct labels of the dashed and solid lines. i.e.,  the solid line is the posterior mean. And dashed line is the objective function. 

Section 6.8.1, Page 308, Line 14 : "quantify the number[s] of hours"... remove 's' from numbers  

Section 6.8.2.1, Page 309, Line 27.5 " be willing to put [ ] extra hours"  add "in" i.e., "to put in extra hours"

Section 6.8.2.2, Page 310, Line 8.5: missing "us" or "one", i.e., ..."optimal transport allows [ ] to recover..."

Section 6.8.3.1, Page 312, Line 13: two small typos in this sentence  i.e., ..."sense that it allows [ ] to restrict our attention [on] c-concave"... missing 'us' between 'allows' and 'to restrict', and replace 'on' with 'to' 

Section 6.9.1.1, Page 316, Line 42.5: missing "we", i.e., "...[ ] will explore the manner..."

Section 6.9.6, Page  327, Line 16: undo capitalization of "S" in section title i.e., "feature Selection" -> "feature selection"

Section 6.9.6, Page 327, Line 40:  missing 'a' i.e., "diameter of [ ] set"

Section 6.9.6.1, Page 328, Line 33.5 : missing the word "in"  i.e., "not present [ ] the summary 

Section 6.9.6.1, Page 329, Line 4 : Replace 'of' with *** in the phrase "offers [of] a coreset property"... where *** depends on the intent of the sentence, but perhaps "offers a guarantee of a coreset property" ? 

Section 6.9.6.1, Page 329, Line 39: Missing parentheses around  β > 0

**Comment by murphyk** [comment]
fixed, thanks!
