### ISSUE TITLE
Broken Link in Figure 8.5

### ISSUE THREAD

**Issue by apoorvagnihotri** [probml/pml2-book#24]
![image](https://user-images.githubusercontent.com/22618985/157801480-0af4dfe7-6dd6-4839-bd34-fcb5592aa366.png)

Under section 8.1.4.1 Filtering, the link to kf_tracking_demo.py is given as https://github.com/probml/JSL/blob/main/jsl/demos/kf_tracking_demo.py, instead, it should be https://github.com/probml/JSL/blob/main/jsl/demos/kf_tracking.py

**Comment by murphyk** [comment]
fixed, thanks
