### ISSUE TITLE
Brier Score definition should be negated

### ISSUE THREAD

**Issue by chrisyeh96** [probml/pml2-book#241]
**Book version:** 2023-04-01

**Issue:** The Brier score (equation 14.16) is not a proper scoring rule as written. It needs a negative sign in front.

**More details:** Equation 14.16 is equivalent to the score function defined in Brier's original paper. However, Brier's paper defined the score function such that lower scores are better. In contrast, in the modern definition of proper scoring rules (including this book's own definition), larger scores are better. Hence, Equation 14.16 needs a negative sign in front.

**Comment by murphyk** [comment]
good catch. Fixed.
