### ISSUE TITLE
Score function ambiguous, typos, 2023-04-01 version

### ISSUE THREAD

**Issue by dogandzic** [probml/pml2-book#242]
Equation (3.39) is gradient of log likelihood with respect to $\boldsymbol{\theta}$, defined as a score function. This is a common statistical definition.
Also a typo: (3.41) should have the same subscript in the exponent as (3.40). Also what about (3.43) and other places?

Then, equation (24.17), also called the score function, but now gradient of log likelihood with respect to $\boldsymbol{x}$.

I think people are aware of this inconsistency, but still I think it should be commented on somewhere. Or given a somewhat different name to differentiate the two score functions.

**Comment by djsutherland** [comment]
Something some papers have done is call the gradient-wrt-x one the "Hyvärinen score," after the original score matching paper (Hyvärinen 2005).

That paper introduced it as
> For simplicity, we call this the score function, although according [to] the conventional definition, it is actually the score function with respect to a hypothetical location parameter (Schervish, 1995).

**Comment by murphyk** [comment]
good point. I have clarified this in the latest version (to be uploaded soon).
