### ISSUE TITLE
citations for kernel stein discrepancy p. 854

### ISSUE THREAD

**Issue by arthurgretton** [probml/pml2-book#245]
There are a couple of issues with the citations to the kernel Stein discrepancy on p. 254, lines 4-8.

First, Gorham and Mackey [GM15]  did not introduce the kernel Stein discrepancy. They defined a Langevin Stein discrepancy in terms of a different function class, namely The W^{2,\infty} Sobolev ball. 

Second, the goodness-of-fit test based on the Kernel Stein Discrepancy was simultaneously introduced in the same ICML 2016 conference by [LLJ16] and in the paper:

Chwialkowski, Kacper and Strathmann, Heiko and Gretton, Arthur
A Kernel Test of Goodness of Fit
In: International conference on machine learning. 2016, pp. 2606--2615

BTW, there is a review paper here with further details of recent developments in Stein's method and computational statistics:
https://projecteuclid.org/journals/statistical-science/volume-38/issue-1/Steins-Method-Meets-Computational-Statistics--A-Review-of-Some/10.1214/22-STS863.short

Best,
Arthur

**Comment by djsutherland** [comment]
Just a note that this is about latex page 854 for the 2023-4-1 version (inside 24.5.2, Minimizing the Stein discrepancy).

**Comment by murphyk** [comment]
Fixed. (FWIW, Yang Song wrote this section :)
