### ISSUE TITLE
Conformal Prediction

### ISSUE THREAD

**Issue by chrisyeh96** [probml/pml2-book#248]
Book version: 2023-04-01

On page 580 just after equation (14.50), the book writes
> where the probability is wrt the true distribution P*(xn+1, yn+1)

I think this should say
> where the probability is wrt the true distribution P*((x1,y1), ..., (xn+1, yn+1))

In other words, the probability in equation (14.50) also includes the randomness that comes from sampling the calibration data.

**Comment by murphyk** [comment]
Yes, good catch. Fixed.
