### ISSUE TITLE
Some typos in Chapter 20, version 2023-04-01

### ISSUE THREAD

**Issue by RohanKarthikeyan** [probml/pml2-book#249]
(1) There are a few typos in Section 20.2:
> 1st line: ...many kinds of generative model**s**...

> 2nd line: - which use deep neural network**s**...

(2) In the first line of the caption of Figure 20.1: 
> Summary ... deep generative model**s**...

(3) We can update the URL of the [Wen21] bibliography entry to https://lilianweng.github.io/posts/2021-07-11-diffusion-models/

(4) There is a typo in page 767, line 26: 
> ... see e.g., [Ngu+19]). Gen**e**rative models can ...

(5) There is a typo in page 774, line 17 (remove the apostrophe in __it's__):
> ... learning "in it's head"...

**Comment by murphyk** [comment]
fixed, thx
