### ISSUE TITLE
Small Typo in Section 8.1.2 **Example: Casino HMM**

### ISSUE THREAD

**Issue by apoorvagnihotri** [probml/pml2-book#25]
![image](https://user-images.githubusercontent.com/22618985/157801764-725c9975-d0f7-4221-b52d-07630c879fd1.png)

The last sentence, "In a temporal model, there are several kinds of posteriors we may want to **computes**, as we discuss in Section 8.1.4", "computes" should be "compute". Further what it means by "In a temporal model" isn't clear.

**Comment by murphyk** [comment]
fixed, thanks
