### ISSUE TITLE
Typo?: Eq. 8.82; Page 365; Vers. 2023-04-01

### ISSUE THREAD

**Issue by larschrj** [probml/pml2-book#251]
Eq. 8.82 in Normal(z_{t+1} | mu_{t | T}, Sigma_{t | T})

Following corrections?

mu_{t | T} -> mu_{t+1 | T}
Sigma_{t | T} -> Sigma_{t+1 | T}

**Comment by murphyk** [comment]
you are right, thx. Fixed.
