### ISSUE TITLE
Typo?: Algorithm 8.2 Line 6; Page 363; Vers. 2023-04-01

### ISSUE THREAD

**Issue by larschrj** [probml/pml2-book#254]
Algorithm 8.2 Line 6 is:
GaussMoments(\mu_{t|t-1}, \Sigma{t|t-1}, F_t, B_t u_t + b_t, Q_t)

Should be as in Eq. 8.61 (?):
GaussMoments(\mu_{t|t-1}, \Sigma{t|t-1}, H_t, D_t u_t + d_t, R_t)

**Comment by murphyk** [comment]
fixed
