### ISSUE TITLE
y-axis scale adjustment, Figure 8.2, Page 354, Vers. 2023-04-01

### ISSUE THREAD

**Issue by gustavodemari** [probml/pml2-book#255]
**Book version**: 2023-04-01

Chapter 8, Section 8.1, Figure 8.2

**Issue**: The y-scale of Figure 8.2. a) is different from Figure 8.2. b) and c)

**Solution**: Set the same y-scale for the 3 figures.

![image](https://github.com/probml/pml2-book/assets/4651184/c0049b0a-a16c-445d-a563-f92d2f4aeec4)

**Comment by murphyk** [comment]
This is a good idea, but it's really hard for me to change the figures now (due to pdf->cmyk issues).

**Comment by murphyk** [comment]
Also, it seems there are some issues reproducing this plot using dynamax - I have lost the original script, and the above link uses a different seed :(
