### ISSUE TITLE
Typo: Section 4.3.1.1 (Hammersley-Clifford Theorem)

### ISSUE THREAD

**Issue by chsahit** [probml/pml2-book#256]
Book Version: 04-01-23 Draft. Under equation 4.70 (Page 166 in the latex/print page number)
In the parenthetical aside it is written: "Note that the theorem only holds for positive distributions". But this is followed up with $p(x) \geq 0$. I believe it should read $p(x) > 0$. (i.e strict inequality)

**Comment by murphyk** [comment]
fixed, thanks
