### ISSUE TITLE
The bound in VI is concave (and other typos/errors if found)

### ISSUE THREAD

**Issue by maremita** [probml/pml2-book#257]
[Version: 2023-04-01]

In page 451, just before Algorithm 10.4:

> Convergence is guaranteed since the bound is **convex** wrt each of the factors $q_i$ [Bis06, p. 466].

The bound (ELBO) should be **concave** wrt each of the factor $q_i$.

Thanks.

**Comment by maremita** [comment]
[Version: 2023-04-01]

In the bibliography, reference : [Gre98] P. Green. “ Reversible Jump Markov Chain Monte Carlo computation and Bayesian model determination”. In: Biometrika 82 (**1998**), pp. 711–732.
The year of publication should be **1995**.

[Link to the paper](https://academic.oup.com/biomet/article-abstract/82/4/711/252058)

Thanks.

**Comment by murphyk** [comment]
fixed
