### ISSUE TITLE
Equation 7.9: conditioning the expectation on data D or on model M for marginal likelihood?

### ISSUE THREAD

**Issue by maremita** [probml/pml2-book#264]
[Version: 2023-04-01]

In equation 7.9 (page 340) $\mathbb{E}\left[ g(\boldsymbol{\theta})|\mathcal{D} \right]$ should be $\mathbb{E}\left[ g(\boldsymbol{\theta})|M \right]$?

Thanks.

**Comment by maremita** [comment]
In [Martin et al. 2020](https://arxiv.org/abs/2004.06425), the marginal likelihood of the model $M$, $p(\boldsymbol{y}|M)$, is given by the Equation (5):
$$\mathbb{E}\left[ g(\boldsymbol{\theta}) | M \right] = \int_{\boldsymbol{\Theta}}  g(\boldsymbol{\theta}) p(\boldsymbol{\theta} | M) \texttt{d}\boldsymbol{\theta},$$
wrt the prior $p(\boldsymbol{\theta} | M)$ ($\boldsymbol{y}$ is the observed data here).

**Comment by murphyk** [comment]
Yes, good catch! Fixed.
