### ISSUE TITLE
Minor typo in line 27, page 354, Figure 8.2 comments, Section 8.1.1, version 2023-04-01

### ISSUE THREAD

**Issue by zhaoyoubing** [probml/pml2-book#265]
Original: "Red cross is the posterior mean"
But you cannot find any red crosses in Figure 8.2(b) but only the red line

And according to line 4 in page 359 "The red line shows the posterior mean estimate of the location", "Red cross" should be "Red line"

**Comment by murphyk** [comment]
fixed
