### ISSUE TITLE
Possible omitted definition in chap 36

### ISSUE THREAD

**Issue by Duane321** [probml/pml2-book#268]
Edition: 2023-04-01, Advanced Topics

In the following from Chap 36.4.2.3, p.1189:

![image](https://github.com/probml/pml2-book/assets/19956442/965bf51a-1347-4edf-a3f1-bdc367f20b17)

I believe the following was omitted:

![image](https://github.com/probml/pml2-book/assets/19956442/1ed5d94c-c95a-4da3-9d17-0abe8a81e8a6)

Or just the definition of **X**_i. Another possibility is this is defined somewhere I haven't read or it's assumed that the reader can figure this out.

**Comment by murphyk** [comment]
I'll ask the authors.

**Comment by vveitch** [comment]
You're correct, thanks!

**Comment by murphyk** [comment]
fixed
