### ISSUE TITLE
Possible typo on p.1189

### ISSUE THREAD

**Issue by Duane321** [probml/pml2-book#269]
Edition: 2023-04-01, Advanced Topics

Not positive about this one, but I _think_ tau, highlighted in red, should be 0.

![image](https://github.com/probml/pml2-book/assets/19956442/afc6df36-57ba-409b-8ca5-be14aac4565a)

Otherwise, our estimator involves knowing the true tau? And it doesn't seem it would be an estimator, since if the tau AIPTW-estimator happen to equal the truth (tau), then the term with the red box would be zero.

**Comment by murphyk** [comment]
I'll ask the authors.

**Comment by vveitch** [comment]
Nice catch; the left hand side of this equation should have had a - \tau

**Comment by murphyk** [comment]
fixed
