### ISSUE TITLE
Issue in eq 36.42

### ISSUE THREAD

**Issue by Duane321** [probml/pml2-book#270]
Edition: 2023-04-01, Advanced Topics

I believe eq 36.42:

![image](https://github.com/probml/pml2-book/assets/19956442/7d94767f-4604-4976-b496-fcde4c46d7aa)

should be this

![image](https://github.com/probml/pml2-book/assets/19956442/a0932838-5d48-4664-8c60-24bee30fcc3a)

Or something else. The point is, xi should get multiplied by P(x)

**Comment by murphyk** [comment]
I'll ask the authors.

**Comment by vveitch** [comment]
You're correct, this was a typo. Thanks for the catch!

**Comment by murphyk** [comment]
fixed
