### ISSUE TITLE
Possible issue in eq 36.115

### ISSUE THREAD

**Issue by Duane321** [probml/pml2-book#275]
Edition: 2023-04-01, Advanced Topics

I could merely be confused, but it seems there is a mismatch between the equations in red:

![image](https://github.com/probml/pml2-book/assets/19956442/491f493e-c0c2-4720-ae41-56b1c9a52c6b)

Shouldn't p(a) appear in 36.115? It seems like we might be trying to accomplish that with 1/|A|, but I don't believe 1/|A| = p(a)

**Comment by murphyk** [comment]
I'm not sure. I'll ask @vveitch

**Comment by murphyk** [comment]
Hi @vveitch .I'm currently doing a pass of bug fixes, I will check in the source latex by EOD, please ping me before pulling :)

**Comment by vveitch** [comment]
in that case, I'll just do tomorrow morning :)

**Comment by murphyk** [comment]
I just committed all the changes. Please check your email for some more context :)

**Comment by murphyk** [comment]
fixed
