### ISSUE TITLE
Typo in Section 3.5.2.3, pg.105, version 2023-08-15

### ISSUE THREAD

**Issue by Igodlab** [probml/pml2-book#282]
There is a typo in the exponent of the std in the FIM for the univariate Gaussian in eq. (3.2.34), the bottom-right element of the matrix should be: 2/σ^4 rather than 2/σ^2. See [1].

Also, the determinant right after this equation should be proportional to σ^(-3) rather than σ^2. See [2].

The corrected terms in LaTex are:
[1] $2/\sigma^4$
[2] $\sqrt{\det(\mathbf{F}(\boldsymbol{\theta}))}=\frac{\sqrt{2}}{\sigma^3}$

**Comment by murphyk** [comment]
actually I think we are both wrong.
I think it should be this (assuming 3.62 is correct)

<img width="679" alt="Screenshot 2024-06-26 at 5 53 03 PM" src="https://github.com/probml/pml2-book/assets/4632336/115439d5-7563-4dd2-be4f-d385fea800a8">
