### ISSUE TITLE
Typo in Section 12.5.4, pg. 513, version 2023-08-15

### ISSUE THREAD

**Issue by samsartor** [probml/pml2-book#283]
Equation 12.77 for the MH acceptance probability uses $-\mathcal{H}(\mathbfit{\theta}^\ast, \mathbfit{v}^\ast) + \mathcal{H}(\mathbfit{\theta}\_{t-1}, \mathbfit{v}\_{t-1})$ immediately after asserting that $\mathcal{H}$ (the total energy) is constant. Should this be the potential energy $\mathcal{E}$ instead?

**Comment by murphyk** [comment]
The idea of the MH acceptance is to ensure that H is constant even as we change theta,v.
So I think it is correct.
