### ISSUE TITLE
Inaccuracy regarding the release of Google's chatbot

### ISSUE THREAD

**Issue by khisr0w** [probml/pml2-book#284]
On the (latex) page 816 of version 2023-08-15 mentions:
"Indeed, these concerns are why Google has not (at the time of writing) released its version of ChatGPT, known as LaMDA"
Which seems outdated information since, Google has released their version of ChatGPT.
Since the book is still being edited, I thought maybe this needs to be amended.

**Comment by murphyk** [comment]
Good point. I removed that comment.
