### ISSUE TITLE
Issue in Gibbs sampling for Ising models (page 501), version 2023-08-15

### ISSUE THREAD

**Issue by davideC00** [probml/pml2-book#290]
Hi,

there is an issue in the highlighted phrase:
![image](https://github.com/probml/pml2-book/assets/44260691/bed813ce-bd8b-47b7-8993-4b67dfb2bd8f)

If $`x_i \in  \{0,1\}`$, the conditional distribution in the equation 12.27 is $σ(2J(a_i-d_i))$. I think the problem is that the definition $\eta_i=x_i(a_i-d_i)$ works only if $`x_i\in \{-1,1\}`$ but it is has been used also for  the case $`x_i \in  \{0,1\}`$

**Comment by davideC00** [comment]
there is a error here also (same paragraph):

![image](https://github.com/probml/pml2-book/assets/44260691/2170e87b-d5cd-44e3-8cd0-d3d148b8f463)

It should be a plus sign

**Comment by murphyk** [comment]
thanks! Fixed.
