### ISSUE TITLE
Typo in paragraph equations, pg.191, version 2023-08-15

### ISSUE THREAD

**Issue by Igodlab** [probml/pml2-book#296]
Minor typo in Section 4.4.2.2 Deformable parts model. 
The sub-index of the distance in the 'For example...' sentence of the second paragraph is `and $d(y_i , y_i )$
is the distance between parts $i$ and $j$` but sub-indexes should be different: $d(y_i,y_j)$

**Comment by murphyk** [comment]
fixed
