### ISSUE TITLE
Missing apostrophe in 18.24 and 18.26

### ISSUE THREAD

**Issue by thomvolker** [probml/pml2-book#302]
Dear Kevin, 

Thanks for the wonderful book! I noticed a small typo in Eq. 18.24, where the apostrophe for the second $x_2$ is missing $(x^\top x')^2 = (x_1 x_1' + x_2 x_2')^2 = (x_1 x_1')^2 + \underline{(x_2 x_2)^2} + 2(x_1 x_1')(x_2 x_2')$. 

The same occurs in Eq. 18.26, first term in the second line.

**Comment by murphyk** [comment]
fixed
