### ISSUE TITLE
Version 2023-08-15, 26.2.2: minimization vs maximization of the Jensen-Shannon divergence

### ISSUE THREAD

**Issue by tstafylakis** [probml/pml2-book#310]
26.2.2 Density ratio estimation using binary classifiers:
The authors described V as "minimization of the Jensen-Shannon divergence". However, they refer to eq. 26.10 which optimizes the objective with respect to the parameters of the critic/discriminator. Therefore it should be maximization of the JS divergence.

**Comment by murphyk** [comment]
fixed, thx
