### ISSUE TITLE
Version 2023-08-15, several typos in chapter 25 diffusion models

### ISSUE THREAD

**Issue by yuanzhi-zhu** [probml/pml2-book#317]
- In Figure 25.2, the right ) should be outside of {t+1}
- In section 25.2.4, several \hat is missing. (1) "We usually set $\hat{\alpha}_t =$ ..." after eq. (25.26); (2) "...SNR function, and $z_t=...$" after eq. (25.28); (3) "In particular, let $z_v=$..." before eq. (25.29).
- In section 25.4.4, it should be $f(x_t,t)$ instead of $f(x,t)$ in eq. (25.54); And it should be "if we set $f(x_t, t) = -\frac{1}{2}\beta(t) x_t$ ..." right after (a missing subscript $t$ again and a missing $x_t$).
- After eq. (25.68), it should be $x_{t-1}=j$ instead of $x_{t-1}=k$ in the definition of $[Q_t]_{ij}$.

**Comment by murphyk** [comment]
Fixed, thanks!
