### ISSUE TITLE
Version 2023-08-15 Section 12.8.2 (RJMCMC example) typos

### ISSUE THREAD

**Issue by v4ve** [probml/pml2-book#318]
- Either substitute \alpha with \beta in equation (12.139)  at p531 (latex page 563/1354) (quickest fix)

- Or, at p532 (latex page 564/1354):
  - above equation (12.141): we require $|| \mu_1 - \mu_2|| < 2 \alpha $ instead of 2 \beta
  - (12.142) \beta should be \alpha
  - below (12.142): should be "| \det J_{split} |= 2\alpha" instead of 2 \beta
  - below (12.143):  should be "where |det J_{merge} | = 1/(2\alpha)" instead of \beta

**Comment by murphyk** [comment]
thanks
