### ISSUE TITLE
Typo v2024-06-26: Eq. 6.145

### ISSUE THREAD

**Issue by larschrj** [probml/pml2-book#329]
Seems to me like the last term in Eq. 6.145 is missing an expectation E in front of the log(p(y|θ)).

Should it not be E[log(p(y|θ))]?

Amazing book ♥️

**Comment by murphyk** [comment]
actually log p(y|theta) is independent of z, so sum_z q(z) log p(y) = [sum_z q(z)] log p(y) = 1 log p(y)

**Comment by larschrj** [comment]
Thanks for pointing that out 🙂
