### ISSUE TITLE
v2024-06-26: Derivation issues with 4.40 at page 157

### ISSUE THREAD

**Issue by hiraksarkar** [probml/pml2-book#347]
Equation (4.40) seems to be proportional to (4.39), and not equal. 
$$p(x_n|y_n,\theta_x) = \frac{p(x_n,y_n|\theta_x)}{p(y_n|\theta_x)}$$

Now given $x_n$ is observed $y_n \not \perp \theta_x | x_n$. 

Therefore $p(x_n|y_n,\theta_x)  \neq p(x_n,y_n|\theta_x)$

**Comment by murphyk** [comment]
fixed, thx
