### ISSUE TITLE
Sign error in Equations 25.6, 25.7 [version 2022-03-14].

### ISSUE THREAD

**Issue by gileshd** [probml/pml2-book#52]
I think there is a sign error in Equations 25.6 and 25.7 (Section 25.2 lines 14, 15), page 865 (latex).

**In short:**
The text currently reads:
> l(theta) = D_KL(p_data || p_theta) - constant

When I think it should read:

> l(theta) = constant - D_KL(p_data || p_theta).

**In more detail:**
The equations state that the expected log likelihood, $l(\theta) = \mathbb{E}_{x \sim p_{data}} [ log p_{\theta} (x) ]$, is equal to the KL divergence between, $p_{data}$ and $p_{\theta}$, minus the expected log likelihood of the data distribution, $\mathbb{E}_{x \sim p_{data}} [log p_{data}(x)]$.

With respect to the parameters, $\theta$, this is equal to the KL divergence minus a constant.

I think that it should be the other way around. The expected log likelihood is equal to a constant minus the KL divergence, hence why maximising the log likelihood is equivalent to minimising the KL divergence.

I might be mistaken though, apologies if I have got things muddled up.

**Comment by gileshd** [comment]
It also looks like the KL divergence terms are formatted differently in these equations to the rest of the book.

Here: $D_{KL}$.
Everywhere else: $D_{\mathbb{KL}}$.

**Comment by murphyk** [comment]
fixed, thanks
