### ISSUE TITLE
Error in Equation 25.14 [version 2022-03-14]

### ISSUE THREAD

**Issue by gileshd** [probml/pml2-book#53]
I think there might be a mistake in Equation 25.14 (Section 25.2 line 42, page 865 (latex)).

In the text the partition function appears inside the exponential but I think it should be outside, something more like:
$$
\int \exp (- E_{\boldsymbol{\theta}}(\mathbf{x})) Z_{\boldsymbol{\theta}}^{-1} (-\nabla_{\boldsymbol{\theta}} E_{\boldsymbol{\theta}}(\mathbf{x}))d\mathbf{x}.
$$

**Comment by murphyk** [comment]
fixed, thanks
