### ISSUE TITLE
Typos in Chapter 10 on Variational Inference [version 2022-02-17] 

### ISSUE THREAD

**Issue by manuelhaussmann** [probml/pml2-book#55]
(Findings due to Aalto Seminar students)

Comments are formatted via LaTeX.

Given the old version some of them are probably outdated.

- p394, l29: equation (10.22) uses $\cdots$ instead of $\ldots$ in the $\tilde p(\cdot)$
- p397, l33: the likelihood has a misplaced equal sign after the product 
- p399, l43: equation (10.59) uses $\int\int$ (\verb$\int\int$) instead of $\iint$ (\verb$\iint$)\footnote{requires amsmath}
- p408, l20: 'we assume the a specific functional form for q'
- p408, l45: 'To derive this, we [use] the fact that...'
- p409, l6, e10.103: $\left[\log \frac{p_{\boldsymbol{\theta}}(\boldsymbol{z}, \boldsymbol{z}}{q_{\boldsymbol{\psi}}(\boldsymbol{z})}\right] d \boldsymbol{z} \to \left[\log \frac{p_{\boldsymbol{\theta}}(\boldsymbol{z}, \mathcal{D})}{q_{\boldsymbol{\psi}}(\boldsymbol{z})}\right] d \boldsymbol{z}$
- p412, l15: ``if if" $\to$ ``if``
- p428, l42: ...a more complex \sout{distribution} final distribution. 
- p432, l9: ``Intuitvely" $\to$ ``Intuitively``
- p432, l20: 'Another approach \sout{it} is to use...'

**Comment by murphyk** [comment]
fixed, thanks
