### ISSUE TITLE
Typos in Chapter on Monte Carlo [version 2022-02-28]

### ISSUE THREAD

**Issue by manuelhaussmann** [probml/pml2-book#56]
(Findings due to Aalto Seminar students)

Comments are formatted via LaTeX.

Given the old version some of them are probably outdated.

- P450, l40,e11.12: missing parenthesis, (because ... ) 
- p452, l31: Dangling "$<$" at end of line
- p454, l37: equation 11.30, $\int \varphi(x)\pi(x)\pi(x) \: dx \rightarrow \int \varphi(x)\pi(x) \: dx $
- p455, l34: 'and $Z=p(\boldsymbol{y} .)$' $\to$   'and $Z=p(\boldsymbol{y}))$'
- p456, 2: "were we have" instead of "where we have"
- p456, 4: equation missing indexing?$\tilde{w}_n  = \frac{\tilde{\gamma}(x)}{q(x)} \rightarrow \tilde{w}_n  = \frac{\tilde{\gamma}(x_n)}{q(x_n)}$
- p456, l45: we cannot do [it] so easily
- p458, l43: "tractable" instead of "tractably".
- p460, 30: ``variance is reduce" $\to$ ``variance is reduced"
- p469, l41: it finds on[e] of the most likely
- p487, l14: t-1 is not in subscript of v
- p487 l39 - last line of Algorithm 14, $\bm{\theta}_{t+1}=\bm{\theta}^* \rightarrow \bm{\theta}_{t}=\bm{\theta}^*$ and $\bm{\theta}_{t+1}=\bm{\theta}_t \rightarrow \bm{\theta}_{t}=\bm{\theta}_{t-1}$
- p490 l9 - last line of Algorithm 15, $\bm{\theta}_{t+1}=\bm{\theta}^* \rightarrow \bm{\theta}_{t}=\bm{\theta}^*$ and $\bm{\theta}_{t+1}=\bm{\theta}_t \rightarrow \bm{\theta}_{t}=\bm{\theta}_{t-1}$

**Comment by murphyk** [comment]
fixed, thanks
