### ISSUE TITLE
Typos in Chapter on Bayesian Neural Networks [version 2022-02-28]

### ISSUE THREAD

**Issue by manuelhaussmann** [probml/pml2-book#57]
(Findings due to Aalto Seminar students)

Comments are formatted via LaTeX.

Given the old version some of them are probably outdated.

- p619: (17.2) lacks the $\varphi$ in the outermost bracket. The same also applies to several later equations of the MLP setup, e.g., (17.7), (17.8)
- p622, l22: the reference [FBW21] uses NIPS instead of NeurIPS as the abbreviation in the bibliography (might also apply to other papers)
- p623 l5 translation invariance $\rightarrow$ translation equivariance
- p624, l6: broken reference 
- p624, l34: "where as the original Hessian in Equation (17.13)" ends midsentence.
- p624, l46: ths $\to$ this
- p626, l31: Reference to the same section?
- p637 l28 practicioner $\rightarrow$ practitioner
- 640 l42 Equation (17.27) $\mathbb{KL}QP \rightarrow D_{\mathbb{KL}}(Q||P)$

**Comment by murphyk** [comment]
fixed, thanks
