### ISSUE TITLE
Typos in Chapter on Variational Autoencoders [version 2022-03-14]

### ISSUE THREAD

**Issue by manuelhaussmann** [probml/pml2-book#58]
(Findings due to Aalto Seminar students)

Comments are formatted via LaTeX.

Given the old version some of them are probably outdated.

p792, l21: $\operatorname{Ber}(x_{d} \mid \boldsymbol{\sigma}(d_{\boldsymbol{\theta}}(\boldsymbol{z}))\to \operatorname{Ber}(x_{d} \mid \boldsymbol{\sigma}(d_{\boldsymbol{\theta}}(\boldsymbol{z})))$
p793 l7 is is $\rightarrow$ is
p795 l25 gradent $\rightarrow$ gradient
P801 l7 Equation 22.60 $q_{\bm{\phi}}(\mathbf{z}|\mathbf{x}) \rightarrow q_{\mathcal{D},\bm{\phi}}(\mathbf{z}|\mathbf{x})$
p802, l8: $\hat{\boldsymbol{x}}=d_{\boldsymbol{\theta}}(\boldsymbol{x}) \to \hat{\boldsymbol{x}}=d_{\boldsymbol{\theta}}(\boldsymbol{z})$
p809, l34: fixd $\to$ fixed
p809, l42: is $\to$ if
p811, l34: $ \operatorname{diag}(\sigma_{\boldsymbol{\phi}}^{2}(\boldsymbol{x})) \to  \operatorname{diag}(\sigma_{\boldsymbol{\phi}}^{2}(\boldsymbol{x})))$ 
p801 l21 typicaly $\rightarrow$ typically
p815, l29: Ther $\to$ There
p815 l44, minimized the ELBO $\rightarrow$ maximized the ELBO
p817, l29: the the $\to$ the 
p818 l36: is $\rightarrow$ it
p819, l41: identifiabie $\to$ identifiable

**Comment by murphyk** [comment]
Thanks. Re p801 (sec 22.2.7) -  It seems I was not very precise with the aggregated posterior notation. I have now changed it to the attached - does this look correct now?
<img width="465" alt="Screen Shot 2022-04-10 at 4 25 18 PM" src="https://user-images.githubusercontent.com/4632336/162644430-d499e706-3743-44a7-93e8-1bbe0a6d9184.png">
