### ISSUE TITLE
Typos in Chapter on Auto-regressive Models [version 2022-03-14]

### ISSUE THREAD

**Issue by manuelhaussmann** [probml/pml2-book#59]
(Findings due to Aalto Seminar students)

Comments are formatted via LaTeX.

Given the old version some of them are probably outdated.

- p838, l43: ``However, at at test" $\to$ ``However, at test"
- p839, l24: ``This is decoder-only" $\to$ ``This is a decoder-only"
- p839, l36: ``tasks that is has never" $\to$ ``tasks that it has never"

**Comment by murphyk** [comment]
fixed, thanks
