### ISSUE TITLE
Page 128 Figure 4.2 typos [version 3-14-2022]

### ISSUE THREAD

**Issue by mkinney-mitre** [probml/pml2-book#60]
Figure 4.2 does not have the same probabilities that are described in section 4.2.2.2. I believe the figure is incorrect and the text in section 4.2.2.2 is correct. Text is

The CPTs for the student network are shown next to each node in Figure 4.2. For example, we see
that if the class is hard (D = 1) and the student is dumb (I = 0), the distribution over grades A,
B and C we expect is p(G|D = 1, I = 0) = [0.05, 0.25, 0.7]; but if the student is intelligent, we get
p(G|D = 1, I = 1) = [0.5, 0.3, 0.2]

but figure is
![image](https://user-images.githubusercontent.com/85962924/161969111-8f50781d-5538-4fec-bc6c-24f2aea09bc2.png)

**Comment by murphyk** [comment]
I created https://github.com/probml/pyprobml/issues/733 to track this.

**Comment by murphyk** [comment]
fixed
