### ISSUE TITLE
Typo in 7.5

### ISSUE THREAD

**Issue by kjohnsen** [probml/pml2-book#61]
- [ ] in equation 7.29 there's a missing division sign (slash) on the bottom in the middle
- [ ] In section 7.5 (evaluating approximate inference algorithms), lines 44-45 of page 320 as of the April 1 draft, it says "the 3 deterministic methods (Laplace, BP, and EP)." I think it should be "VB" instead of "BP"

**Comment by murphyk** [comment]
fixed, thanks.
