### ISSUE TITLE
minor typos, April 2022-04-01

### ISSUE THREAD

**Issue by dogandzic** [probml/pml2-book#64]
April 2022-04-01 version

p. 851, Alternatively, we can specify an implicit probabilistic
model that defines a stochastic procedure to directly *generates* data

Should be
generate

Also, udpate instead of update:

p. 951, In addition, the above method relies on a conjugate exponential model in order to compute the
marginal likelihood, and *udpate* the posterior parameters

p 115, The *udpate* equation can be interepreted as
follows: we compute the sum of discou

**Comment by murphyk** [comment]
fixed
