### ISSUE TITLE
Error in Equation 5.149 [version 2022-04-01]

### ISSUE THREAD

**Issue by csarron** [probml/pml2-book#65]
<img width="873" alt="Screen Shot 2022-04-14 at 20 48 55" src="https://user-images.githubusercontent.com/8440740/163515274-648c2c85-7fb6-48e3-9695-510a5d562320.png">

the smaller or equal symbol should be greater or equal based on KL divergence definition from equation 5.10.

**Comment by murphyk** [comment]
fixed
