### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by alanwzhao** [probml/pml2-book#67]
April 26 Version, the latex (print) page number.

P313, the second last line above Section 7.2, "and then relying on some inference engine to **the** do the rest of the work", "the" is redundant.

P326, the caption of Figure 8.1, the second "(a)" should be "(b)".

P440, Line 17 and Line 18, in the formulas, I believe both should be N_s instead of S. 
P440, Line 25, after "using Monte Carlo intergration", it should be a period instead of a comma.

P905, the caption of Figure 27.2, it should be "K=5" instead of "K=3".

**Comment by murphyk** [comment]
fixed, thanks
