### ISSUE TITLE
 Typos in Chapter on GANs [version 2022-04-01]

### ISSUE THREAD

**Issue by manuelhaussmann** [probml/pml2-book#68]
(Findings due to Aalto Seminar students)

Comments are formatted via LaTeX. The page numbers follow the printed version.

- p852, snd paragraph: the generative modelcitations. $\to$ The citations does not give an actual citation
- p852, l26: "specified using by deep networks"
- p854, l45: Should probably say "if the ratio is 1 everywhere in the support of $q_{\theta}$"
- p854, l46: "Since we cannot evaluate..." has a repetition of  "we cannot evaluate"
- p859, l42: "Section Section"
- p800, l37: "where $\zeta_\phi$ regularized" is missing an "is"
- p861 l32: Less of an error and more a minor inconsistency. Reproducing Kernel Hilbert Space is here fully written out, while p859,l35 only gives the abbreviation. Switching the two might be better.
- p861, l36: ... vs $\ldots$
- p863 l14 \sout{follow}
- p864 l46 $\text{argmin min}_{\bm{\phi}}L_D(\bm{\phi},\bm{\theta}) \to \text{argmin}_{\bm{\phi}} L_D(\bm{\phi},\bm{\theta})$
- p865, l34: "Section Section"
- p872, l37: subindices error: $G_\phi(E_\xi(x)) = x$ instead of $G_\xi(E_\phi(x)) = x$
- p875 l36, "An similar" $\to$ "A similar"

**Comment by murphyk** [comment]
very helpful, thanks!
