### ISSUE TITLE
Please release supplementary material with main text

### ISSUE THREAD

**Issue by lockmatrix** [probml/pml2-book#70]
I notice that supplementary material is also updated a lot with main text in recent versions, 
but the new version of supplementary material is not released.

**Comment by murphyk** [comment]
it's here.
https://github.com/probml/pml-book/blob/main/pml2/supp2-2022-04-29.pdf
Maybe I should bundle both pdf files in the same release?

**Comment by lockmatrix** [comment]
thx, that will be much better for people follow your github.

**Comment by murphyk** [comment]
Ok, I added supp2.pdf to accompany pml2.pdf in the current release.
This is a much better way to do things, I will use this  in the future :)
