### ISSUE TITLE
Typos [version 2022-04-29]

### ISSUE THREAD

**Issue by lockmatrix** [probml/pml2-book#71]
### 3.1.2 Bayesian statistics
Page 48, line 6
![1651296365(1)](https://user-images.githubusercontent.com/1844843/166092570-11713d5f-0277-491f-958f-3c38f5e94bae.png)
missing "="

### 3.1.5.1 The MAP estimate gives no measure of uncertainty
Page 50, line 22
![1651297436(1)](https://user-images.githubusercontent.com/1844843/166093148-1cfaf610-2cc5-441a-8d05-62826819932e.png)
"See ?? for details."

### 3.2.1 The binomial model
Page 54, line 343
![1651297640(1)](https://user-images.githubusercontent.com/1844843/166093253-b1facb09-a54f-434c-b962-4ab8235ca41d.png)
"If we multiply the Bernoulli likelihood in ??"

### other ??
You can search ?? in pdf, there are many other ??s .

### 5.2.4 Cross entropy and perplexity
(5.90)
![1651297931(1)](https://user-images.githubusercontent.com/1844843/166093405-502344d6-88dd-40cc-8074-66bcee02a3c0.png)
the font size is too small

### Bibliography and Index
I think the font size is too small for printing.

**Comment by murphyk** [comment]
I will fix all the ?? soon.
