### ISSUE TITLE
Chapter 4 (PGMs) Typos [version 2022-05-02]

### ISSUE THREAD

**Issue by gileshd** [probml/pml2-book#72]
## Chapter 4 (Probabilisitic graphical models)

- 4.2.2 - p.96 (latex) line 35: "PGM-D" not previously defined.
	- The term "PGM" is defined at the start of the section, but I don't think PGM-D is ever defined.

- 4.2.4 - p.101 (latex) line 5: $x_B$ should be upper case --> $X_B$.

- 4.2.4.1 - p.102 (latex) line 27: Figure 4.5 caption - variables are upper case in figure (X,Y,Z) but lower case in caption (x,y,z). 

- 4.2.6 - p.106 (latex) line 46: Eq 4.35 - p(h|x) repeated twice at start of equation.
	- p(h|x) = p(h|x) = ...

- 4.2.7.5 - p.112 (latex) line 7: "As example" --> "As an example".

- 4.3 - p.116 (latex) line 32: "PGM-U" not previously defined.
	- This is more obvious from context but like PGM-D it is not defined before use.

**Comment by murphyk** [comment]
fixed, thanks
