### ISSUE TITLE
Chapter 8 & 9 Typos [version 2022-05-02]

### ISSUE THREAD

**Issue by gileshd** [probml/pml2-book#73]
## Chapter 8 (Message Passing)

- 8.7.3.2 - p.359 (latex) line 3: typo "by"-->"bu".
	>We can define multiplication and division in the Gaussian case **bu** using canonical forms, as follows.

## Chapter 9 (Variational inference)

- 9.3.2 - p.384 (latex): 'control variates':
	- "CV" abbreviation appears in text without definition, it is pretty clear from the context what is meant by "CV" but it might be helpful to be explicit.
	- superscripts: eqs 9.117 & 9.118 use "CV" in caps as superscript, eq. 9.119 uses lower case "cv" as superscript.

**Comment by murphyk** [comment]
fixed, thanks
