### ISSUE TITLE
Chapter 24 Typo [version 2022-05-02]

### ISSUE THREAD

**Issue by mnazaal** [probml/pml2-book#74]
24.3 p834 (latex) line 40, Equation ~~24.12~~ 24.14 has a $\log$ missing right after $q(\mathbf{x}_0)$

**Comment by murphyk** [comment]
I don't see the problem. Please provide a screenshot of the erroneous line.

**Comment by mnazaal** [comment]
<img width="787" alt="image" src="https://user-images.githubusercontent.com/18580527/167193340-d8c0321f-4942-4247-a782-36529333881f.png">

**Comment by murphyk** [comment]
got it. fixed, thanks
