### ISSUE TITLE
Section 6.6.1 [2022-02-05]

### ISSUE THREAD

**Issue by skleinbo** [probml/pml2-book#75]
![Screen Shot 2022-05-10 at 13 59 51](https://user-images.githubusercontent.com/19183183/167623638-3216598a-522f-4aaa-879a-3843896b980b.png)

* Line 32: Should read `Q(\theta^t, \theta^t) = LL(\theta^t)` ?
* Line 39: `l` is the same as `LL` ?

**Comment by murphyk** [comment]
fixed, thanks
