### ISSUE TITLE
Typos in Chapter on SSMs [version 2022-05-02]

### ISSUE THREAD

**Issue by manuelhaussmann** [probml/pml2-book#76]
(Findings due to Aalto Seminar students)

Comments are formatted via LaTeX. The page numbers follow the printed version.

- p925, Equation 28.2 missing closing parenthesis at end
- p927, l2: comuting $\to$ computing
- p931, l45 we the $\to$ the
- p932, l39: maxumize $\to$ maximize
- p948, l15 and/dor $\to$ and/or

**Comment by murphyk** [comment]
fixed, thanks
