### ISSUE TITLE
Chapter 8 Issues [version 2022-05-02].

### ISSUE THREAD

**Issue by gileshd** [probml/pml2-book#77]
### Section 8.2

- p. 323 (latex) line 32: z subscript should be uppercase - "z_t" --> "z_T".

- p. 314 (latex) Eq. 8.43: missing "= j" - " p(z_{t+1}|y_{1:T})" --> "p(z_{t+1} = j | y_{1:T})".

- p. 315 (latex) line 26: "If we define \xi..." this line already appears at the top of the page (line 2).

- p. 315 (latex) line 38: A is defined as the transition matrix between z_{t-1} and z_t, while they are equivalent, for consistency with the figure that this sentence is referring to (Figure 8.3) it might be helpful to write it as "A = p(z_t | z_{t+1})".

### Section 8.3 

- p. 320 (latex) Eqs. 8.73, 8.74: This LG-SSM models are defined to include inputs (u_t) and with an autoregressive term (E_t). In the next sentence these terms are all stated to equal to 0 and I don't think they are used at any point in the rest of the section. Given that the full equations are given in Chapter 28, it might be more clear to just drop these terms entirely.
    - If this were done it would be necessary to make the following additional changes for consistency:
        - p. 320 line 45: drop the conditioning on u in the joint p(y,z|u) --> p(y,z).
        - p. 320 Figure 8.6 would have to change, the new form would be identical to Figure 8.1(a).

- p. 321 (latex) line 26,27: The sampling frequency is referred to in the text as \Delta but in Eq 8.75 I think the equivalent term is written as "\Delta t".

- p. 322 (latex) line 3: Typo - "thay" --> "that".

- p. 324 (latex) Eq 8.91: The term h_t has previously been referred to as C_t (e.g. in Eq 8.81).

- p. 324 (latex) line 11: The noise term \epsilon_t was previously labelled r_t (Eq 8.76).

- p. 327 line 46: "using the same island algorithm as in Section 8.2.3.4". I think the corresponding algorithm is called the "divide and conquer algorithm" in Section 8.2.3.4.

### Section 8.4

- p. 331 (latex) Eq 8.145: P(X=x | u), in the rest of this section the notation "Pr(.)" is used for probabilities.

**Comment by murphyk** [comment]
fixed, thanks
