### ISSUE TITLE
Typos in Chapter on BNP [version 2022-05-02]

### ISSUE THREAD

**Issue by manuelhaussmann** [probml/pml2-book#78]
(Findings due to Aalto Seminar students)

Comments are formatted via LaTeX. The page numbers follow the printed version.

- p1013, l28: $T_1,\cdots,T_K$ $\to$ $T_1,\ldots,T_K$
- p1015, l35: $T \in \Theta$ should be $T \subseteq \Theta$
- p1020, Algorithm 33: line 6 is missing a $p(x_i)$ on the right hand side
- p1031, l9: presenta $\to$ present

**Comment by murphyk** [comment]
fixed, thanks!
