### ISSUE TITLE
Minor stylistic request about typesetting norms.

### ISSUE THREAD

**Issue by djmarti** [probml/pml2-book#88]
Norms seem to be written as two consecutive vertical bars (i.e., $||\mathbf{x}||$ is typeset with `||\mathbf{x}||`), instead of using the specific command provided by LaTeX for norms, `\|` (for some reason the github markdown renderer does not show this correctly). The difference is small, but noticeable to pedantics like me:

<img width="200" alt="image" src="https://user-images.githubusercontent.com/13334759/170784974-e2d954d6-9bc3-45fb-854f-ec60cb1828a6.png">

The one on the left is typyset as `||\mathbf{x}||`, the one on the right as `\|\mathbf{x}\|`.

The norm written with `\|` looks cleaner and is consistent with the typographical tradition (just to give an example, that's how norms are typeset in Boyd and Vandenberghe's [*Convex Optimization*](https://web.stanford.edu/~boyd/cvxbook/), which is very carefully edited). It also takes up less space! It may be worth defining something like (see [`amlsdoc`](http://mirrors.ctan.org/macros/latex/required/amsmath/amsldoc.pdf), page 19).
```
\providecommand{\norm}[1]{\lVert#1\rVert}
```
and simply use `\norm{x}`.

I wonder if it would be possible to replace the norms written as `||x||` with `\|x\|` or , better, with `\norm{x}` using the command above.

**Comment by murphyk** [comment]
It's a good idea, but it is  too much work to do by hand and too  hard for me to automatically make this change  (hopefully soon I can train an LLM to do this for me :)

**Comment by djmarti** [comment]
No problem! I completely understand.

El dt., 31 de maig 2022, 8:22, Kevin P Murphy ***@***.***> va
escriure:
