### ISSUE TITLE
Typo p. 622, parameter beta should be boldfaced

### ISSUE THREAD

**Issue by djmarti** [probml/pml2-book#9]
Page 622 (printed on book, not viewer page), line 13-14: the \beta parameter in the evidence should be a bold symbol, to be consistent with the previous text.

Version: 28 Feb 2022.

**Comment by djmarti** [comment]
I'm afraid I don't get what you mean. There is no "capital" beta here.

**Comment by murphyk** [comment]
fixed, thanks
