### ISSUE TITLE
Interpretability (May 18 2022)

### ISSUE THREAD

**Issue by simonjdprince** [probml/pml2-book#94]
Hey -- apologies, got out of the habit of proofing this, but finally got around to it.  I printed this out a while ago, so it may be that some or all of these are fixed by now.  S.

P1013 L4  "don't cause harms"-->"don't cause harm"
P1013 L5 "some harms" --> "some types of harm"
P1013 L9 "Chapter Chapter"-->"Chapter" (a few instances of this, and "Section Section)
P1013 L16 "irreversible harms"--> "irreversible harm"
P1014 L2 "methods" of "interpretability methods"?
P1014 L44 "More broadly..." this is a very long sentence
P1016 L31 "do the explanation" --> "do the explanations"
P1016 L32 "describes of the impact" --> "describes the impact"
P1018 L32 "blackboxes" --> "black boxes"
P1021 L23 "When the model is its explanation" --> "When the model is its own explanation"
P1024 L22 "all inputs predicted to one class" --> "all inputs assigned to one class"
P1034 L26 "provided an interpretability method" --> "given an interpretability method"
P1034 L30 "Figure32.5" --> "Figure 32.5"
P1043 L29 "may enable a person realize" --> "may enable a person to realize"
P1044 L21 "like explanations are simple" --> "like explanations that are simple"
P1044 L29 "Shapely values" --> "Shapley values"

**Comment by murphyk** [comment]
Been and Finale are fixing some of these issues,AFAIK
