### ISSUE TITLE
Suggestions for GP chapter non-code figures

### ISSUE THREAD

**Issue by nipunbatra** [probml/pml2-book#95]
### The following two figures are low-resolution. It may be easy to just redraw them in a vector drawing web service like draw.io

<img width="1311" alt="Screenshot 2022-07-01 at 9 35 21 AM" src="https://user-images.githubusercontent.com/60985/176821464-9bcf6948-66ff-47bf-a998-a801c62292e7.png">

<img width="1309" alt="Screenshot 2022-07-01 at 9 35 38 AM" src="https://user-images.githubusercontent.com/60985/176821470-6af4aa06-e8bb-4224-a314-fa0f68768003.png">

### The following two figures look fairly big (in terms of fonts) compared to text in the book. Perhaps, just scaling them down in LaTeX may improve the visual appeal.

<img width="1366" alt="Screenshot 2022-07-01 at 9 36 03 AM" src="https://user-images.githubusercontent.com/60985/176821628-30945272-1944-49bc-ba38-aab1812c7378.png">

<img width="1369" alt="Screenshot 2022-07-01 at 9 36 29 AM" src="https://user-images.githubusercontent.com/60985/176821637-4cc09a6a-53ce-40bb-a45f-c0172717a3a3.png">

**Comment by murphyk** [comment]
fixed
