### ISSUE TITLE
Symbol confusing in Chapter Gaussian Process 18.2.2 Mercer’s theorem (version 2022-07-01)

### ISSUE THREAD

**Issue by zjowowen** [probml/pml2-book#98]
Hi,
I found the symbol of eigenvector and eigenfunction is somewhat confusing in 18.2.2 Mercer’s theorem, formula 18.33 and 18.34.
In formula 18.33, the vector φ(x_i) = Λ^(1/2) U:i seems to be eigenvector multiplied by a scale lamda.
However, in formula 18.34, φ is denoted as a uniform eigenfunction with inner product of the value Kronecker delta across each other.
(I suggested writing something, so that readers be aware that φ in formula 18.34 and 18.35 is actually uniformed, and is different with that in formula 18.33.)
Another symbol which may cause confusing is that, in formula 18.37, eigenfunction φ is seems to be scaled as that in 18.33.
(I mean, it's not a very big issue for reader who is good at matrix analysis. But for some unskilled reader as I am, it takes some time to figure out what is going here. For example, now that it is not a uniformed eigenfunction, it would not follow as the formula 18.35, of which the inner product is something else, Kronecker delta multiplied by a specific eigenvalue, rather than a  Kronecker delta.)

**Comment by murphyk** [comment]
fixed thanks
