### ISSUE TITLE
Adding constraint to MLE for language model on page 48 version 2022-07-01

### ISSUE THREAD

**Issue by YuchiLiuS** [probml/pml2-book#99]
Between the log-likelihood 2.291 formula, and the optimal values in 2.293, it would probably be clear if we add the constraint:
\sum_{j}\pi_j=1 and \sum_{k}A_{jk}=1
and use Lagrange multiplier to derive the MLE, otherwise can be confusing how we can directly go from 2.291 to 2.293

**Comment by murphyk** [comment]
fixed thanks
